### ISSUE TITLE
your soo talented

### ISSUE THREAD

**Issue by fdsmjkfjires** [dekrypted/Volt-Stealer#1]
love u bro

**Comment by iqlessmemes** [comment]
What does the victom have to do to give you their token?

**Comment by dekrypted** [comment]
> What does the victom have to do to give you their token?

💀

**Comment by PixelatedLagg** [comment]
stolen from: https://github.com/NobodyWouldEverUseThis7/Token-encryption-writeup

**Comment by dekrypted** [comment]
what

**Comment by dekrypted** [comment]
Deleted PixelatedLagg's comment because he's making retarded claims.

**Comment by PixelatedLagg** [comment]
![image](https://user-images.githubusercontent.com/81400034/187040767-ff0095b1-5dd2-4ae2-a269-0ee932c14cf9.png) Original code

![image](https://user-images.githubusercontent.com/81400034/187040786-4c92e9bb-009f-447d-8abc-b2d009e47ab7.png)
Your code with variable names changed

**Comment by PixelatedLagg** [comment]
the author of the original code doesnt even care if you copy/paste it, they just ask that you credit "CC/CL"

**Comment by dekrypted** [comment]
> the author of the original code doesnt even care if you copy/paste it, they just ask that you credit "CC/CL"

First off, pretty much every token stealer has this same module. The token writeup stuff was skidded from someone else, so I didn't really steal from them.

Second, I based this off Hazard Stealer, not this shitty "Token Writeup"

Third, Keyword: Based. I wrote this myself. I just looked at the format of Hazard and implemented a few QoL features and a webhook sender. So hop off my dick 😄

**Comment by PixelatedLagg** [comment]
once again, you are still stealing it from someone. looking through both source codes, it looks like you added a method to send the token info to a webhook and encapsulated the first few variables in a class. not saying what you are doing is bad, just saying that you should credit [people](https://github.com/NobodyWouldEverUseThis7/Token-encryption-writeup) who you borrow code from, especially if you encourage donations 👍

**Comment by dekrypted** [comment]
did you read what i said?

**Comment by PixelatedLagg** [comment]
the token writeup i linked predates the repo you say you take inspiration from. even if you didnt steal from that one repo, you are still taking a supposedly popular token grabber boilerplate and claiming it as your own.

**Comment by dekrypted** [comment]
you clearly didnt read what i said since you said im taking inspiration from that repo. mald harder.
